services:
  db:
    image: mysql:5.7.44
    container_name: MySQL
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - 3306
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    container_name: PMA
    restart: always
    working_dir:
      /www/mysql-with-phpmyadmin/pma
    ports:
      - 8088:80
    environment:
      - PMA_PORT=3306
