version: '3'

services:  
  portainer:
    image: portainer/portainer-ce:2.14.1
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always

volumes:
  portainer_data:
