services:  
  portainer:
    image: portainer/portainer-ce:2.21.1-alpine
    container_name: portainer
    volumes:
      - ./portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
