services:
  db:
    image: mysql:5.7.44
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'At9dAF5a_+pxM&y'
    expose:
      - 3306:3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    environment:
#      - PMA_HOSTS=127.0.0.1
      - PMA_PORT=3306
#      - PMA_USER=root
#      - PMA_PASSWORD=At9dAF5a_+pxM&y
      - PMA_CONTROLUSER=admin
      - PMA_CONTROLPASS=123456
    ports:
      - 8088:80
    working_dir:
      /www/mysql-with-phpmyadmin/pma