services:  
  uptimekuma:
    image: docker-mirror.vivi.moe/louislam/uptime-kuma:1.23.13-alpine
    container_name: uptimekuma
    volumes:
      - ./uptimekuma_data:/app/data
    ports:
      - "3001:3001"
    restart: always
