version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '12344:80'
      - '81:81'
      - '12345:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    # network_mode: host

