version: '3'

services:
  rdb:
    image: redis:7.0.5
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/home/redis.conf
    command: redis-server /home/redis.conf
